ALTER TABLE User ADD COLUMN password VARCHAR(255) NULL;
ALTER TABLE User ADD COLUMN registrationIp VARCHAR(45) NULL;
CREATE TABLE IF NOT EXISTS LoginSession (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  token TEXT NOT NULL,
  deviceId VARCHAR(255) NOT NULL,
  createdAt DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  FOREIGN KEY (userId) REFERENCES User(id)
);